/*DO NOT EDIT THIS FILE - it is machine generated*/
package com.badlogic.gdx.controllers;

/**
 * DO NOT EDIT THIS FILE - it is machine generated
 */
public class ICadeMapping extends ControllerMapping {

    private static ICadeMapping instance;

    ICadeMapping() {
        super(0, 1, UNDEFINED, UNDEFINED, 0, 1, 2, 3, 7, 6, 4, UNDEFINED, 5, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED);
    }

    static ICadeMapping getInstance() {
        if (instance == null)
            instance = new ICadeMapping();
        return instance;
    }
}
